create database pizza_sales;

use pizza_sales;

SELECT 
    *
FROM
    sales_data
LIMIT 10;

-- 1) find the total sales for each pizza category and sort the result
--    in descending order pf total sales 

SELECT 
    pizza_category, SUM(total_price) AS total_sales
FROM
    sales_data
GROUP BY pizza_category
ORDER BY total_sales DESC;

-- 2) find the top 5 best- selling based on total quantity sold 

SELECT 
    pizza_name, SUM(quantity) AS total_quantity
FROM
    sales_data
GROUP BY pizza_name
ORDER BY total_quantity DESC
LIMIT 5;

-- 3) calculate the total number of orders and the total revenue generated from pizza sales 
SELECT 
    COUNT(DISTINCT order_id) AS total_orders,
    SUM(total_price) AS total_revenue
FROM
    sales_data;

-- find the total revenue generated by each pizza category and diplay the categories in 
-- descending order of revenue highest to lowest

SELECT 
    DATE_FORMAT(order_date, '%Y-%m') AS sales_month,
    SUM(total_price) AS monthly_revenue
FROM
    sales_data
GROUP BY sales_month
ORDER BY sales_month;
    
-- 4) calculate the average order valuue of pizza sales 

SELECT 
    SUM(total_price),
    COUNT(DISTINCT order_id) AS average_order_value
FROM
    sales_data;
    
-- 5) Find the total quantity of pizzas sold for each pizza 
--    size and diplay the results from highest to lowest

SELECT 
    pizza_size, SUM(quantity) AS total_quantity
FROM
    sales_data
GROUP BY pizza_size
ORDER BY total_quantity DESC;    

-- 6) find thetotal revenue generated by each pizza category and pizza size

SELECT 
    pizza_category,
    pizza_size,
    SUM(total_price) AS total_revenue
FROM
    sales_data
GROUP BY pizza_category , pizza_size
ORDER BY pizza_category , total_revenue DESC;

-- 7) find the number of orders placed on each date . Display the dates with the 
--    highest number of orders first

SELECT 
    order_date, COUNT(DISTINCT order_id) AS total_orders
FROM
    sales_data
GROUP BY order_date
ORDER BY total_orders DESC;

-- 8) find the top 5 pizzas that generated the highest revenue
SELECT 
    pizza_name, SUM(total_price) AS total_revenue
FROM
    sales_data
GROUP BY pizza_name
ORDER BY total_revenue DESC
LIMIT 5;

-- 9) find the average unit orice for each pizza category . sort the results 
--    from highest to lowest average price

SELECT 
    pizza_category,
    ROUND(AVG(unit_price), 2) AS average_unit_price
FROM
    sales_data
GROUP BY pizza_category
ORDER BY average_unit_price DESC;

-- 10) Find the total revenue generated by each pizza name and category, and show
--     only those groups with revenue  graeater than 10000

SELECT 
    pizza_name,
    pizza_category,
    SUM(total_price) AS total_revenue
FROM
    sales_data
GROUP BY pizza_name , pizza_category
HAVING SUM(total_price) > 10000
ORDER BY total_revenue DESC;

-- 11) classify each pizza order quantity as 'small order' if quantity is 1, 'medium order'
-- if quantity is 2, and 'large order' if quantity is 3or more 

SELECT 
    order_id,
    quantity,
    CASE
        WHEN quantity = 1 THEN 'small order'
        WHEN quantity = 2 THEN 'medium order'
        ELSE 'large order'
    END AS order_size
FROM
    sales_data
LIMIT 20;

-- 12) find the total quality sold for each pizza category

SELECT 
    pizza_category, SUM(quantity) AS total_quantity
FROM
    sales_data
GROUP BY pizza_category
ORDER BY total_quantity DESC;

